name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers the workflow on tags like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # or adopt, zulu, etc.
          java-version: '21'

      - name: Set up Maven 3.6.3
        run: |
          wget https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.zip
          unzip -q apache-maven-3.6.3-bin.zip
          export M2_HOME=$PWD/apache-maven-3.6.3
          export PATH=$M2_HOME/bin:$PATH
          mvn --version

      - name: Generate Changelog
        uses: github-changelog-generator/github-changelog-generator@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: |
            ## Changes
            [CHANGELOG.md](./CHANGELOG.md)
          draft: false
          prerelease: false

      - name: Build with Maven
        run: mvn clean install