name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers the workflow on tags like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Ensure consistency
          java-version: '21'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Generate Changelog
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          config: .github/release-changelog-config.json
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: |
            ## Changes
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false