name: Version Bump and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers the workflow on tags like v1.2.3

jobs:
  bump_version_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Set the new version in pom.xml
        run: |
          mvn versions:set -DnewVersion=${{ env.VERSION }}
          mvn versions:commit

      - name: Update version in plugin.yml
        run: |
          sed -i "s/^version: .*/version: '${{ env.VERSION }}'/" src/main/resources/plugin.yml

      - name: Commit new version
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add pom.xml src/main/resources/plugin.yml
          git commit -m "Bump version to ${{ env.VERSION }}"
          git push origin HEAD:master --follow-tags

      - name: Build with Maven
        run: mvn clean install

      - name: Rename built JAR file
        run: mv target/*.jar target/SkillApi-v${{ env.VERSION }}.jar

      - name: Upload JAR file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: SkillApi-v${{ env.VERSION }}
          path: target/SkillApi-v${{ env.VERSION }}.jar

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release v${{ env.VERSION }}
          body: |
            ## Release v${{ env.VERSION }}
            - This release includes the latest updates and fixes.
          draft: false
          prerelease: false
          files: target/SkillApi-v${{ env.VERSION }}.jar

      - name: Publish to JitPack
        run: |
          curl -X POST "https://jitpack.io/api/builds/com.github.spacemex/SkillApi/${{ env.VERSION }}" \
            -H 'Authorization: token ${{ secrets.JITPACK_TOKEN }}'